version: 2.1
orbs: 
  sonarqube: psl/sonarscanner@0.0.4
jobs:
  sonarscanner:
    steps:
     - run: 
       name: Install Sonarqube sonarscanner
       command: |
        export SONAR_SCANNER_VERSION=4.7.0.2747
        export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        export SONAR_SCANNER_OPTS="-server"
     - run:
       name: Execute Sonarqube sonarscanner
       command: |
        sonar-scanner \
        -Dsonar.projectKey=sonarqube \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://52.208.63.176:9000 
        
workflows:
  version: 2
  sonarqube:
    jobs:
      - sonarscanner:
        context: SonarQube 
          
